### ISSUE TITLE
[Bug Report] KMS issue in Panorama Module

### ISSUE THREAD

**Issue by migara** [PaloAltoNetworks/terraform-aws-swfw-modules#20]
### Describe the bug

The current Panorama module uses a data resource to retrieve the default KMS key alias, however, we are not passing the correct name format to [this resource](https://github.com/PaloAltoNetworks/terraform-aws-swfw-modules/blob/ebd2b4838b9db252b5a84634d3f44353049ddeb2/modules/panorama/main.tf#L27) 

### Module Version

latest

**Comment by lstadnik** [comment]
#21
