### ISSUE TITLE
Enhance Spoke VMs in the examples

### ISSUE THREAD

**Issue by migara** [PaloAltoNetworks/terraform-aws-swfw-modules#34]
Can we please introduce the following changes to the examples globally?

- Move the instance type from t2.micro to t3.micro
- Use Amazon Linux2 AMIs with `ssm-agent` pre-installed so that users can test without having to install bastion hosts? We probably will have to install nginx via user_data

**Comment by lstadnik** [comment]
PR #57 was already merged
