### ISSUE TITLE
[Bug Report] ASG Delicense still requires manual commit in panorama 

### ISSUE THREAD

**Issue by jschelfh-be** [PaloAltoNetworks/terraform-aws-swfw-modules#4]
### Describe the bug

Using ASG automatic de-license option from panorama is working nicely when scaling-in. However it still requires a manual commit in panorama. We have pipelines to push rules to panorama -> firewalls, but the de-license caused the pipeline to fail on the commitAll to the FWs.

Is it possible to include the commit as well ? (the scope of the commit can be limited to the user that is used to connect to panorama specified in the SSM Parameter: /paloalto/vmseries-asg/delicense)

### Module Version

1.0.9

### Terraform version

1.6.2

### Expected behavior

complete automation of delicensing

### Current behavior

requires manual commit

**Comment by migara** [comment]
@seanyoungberg any thoughts on this? Is this something we should take care of?

**Comment by migara** [comment]
The recommendation is to handle this behaviour outside of these modules (i.e. a different step/stage of the CI/CD pipeline)

Closing this for the time being
