### ISSUE TITLE
Combined example no longer matching reference architecture

### ISSUE THREAD

**Issue by seanyoungberg** [PaloAltoNetworks/terraform-aws-swfw-modules#50]
### Is your feature request related to a problem?

The [combined design example](https://github.com/PaloAltoNetworks/terraform-aws-swfw-modules/tree/main/examples/combined_design) (where inbound, outbound, and e/w traffic are all handled by same FWs and centralized inbound traffic) is no longer up to date with current reference architecture.

It is using a previous architecture where inbound traffic was handled with standard L3 "LB sandwich" and FW with SNAT traffic to the backend.

### Describe the solution you'd like

Current [deployment guides](https://www.paloaltonetworks.com/resources/guides/aws-transit-gateway-deployment-guide) are now set to use centralized GWLB inbound endpoints for this traffic. The example should be update to reflect this.

### Additional context

This can lead to deploying architecture patterns that are no longer recommended. Can cause a lot of time debugging to adjust example to meet current architecture.

**Comment by jollymahn** [comment]
Agreed, we need to make sure the only recommended designs are public facing to avoid confusion and unnecessary effort.

**Comment by seanyoungberg** [comment]
Sorry had some confusion here.

1. Meant to reference the centralized examples, not combined
2. The current deployment guide is still using the LB sandwich for centralized so the example matches the reference architecture. Will need to be updated when next iteration of refarch is released but no action needed for now.
